version: "3"
services:
  mongo:
    image: mongo
    container_name: "catalogo-api-mongo"
    restart: "always"
    volumes:
      - ./.dbcache/mongo/data:/data/db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend
  api:
    image: node:10.16-slim
    container_name: "catalogo-api"
    ports:
      - "3000:3000"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "npm start"
    networks:
      - backend

  redis:
    image: redis:5.0.5-alpine
    container_name: "catalogo-api-redis"
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"